export const allowed = [
  'www.idealo.de',
  'www.alza.de',
  'cdn.alza.cz',
  '1603811301.rsc.cdn77.org',
  'www.proshop.de',
  'www.digitalo.de',
  'bot-detector.rebrowser.net',
  'www.notebooksbilliger.de',
  'www.notino.de',
  'www.flaconi.de',
  'www.babymarkt.de',
  'www.conrad.de',
  'api.conrad.de',
  'api-cdn.conrad.com',
  'www.coolshop.de',
  'webshop.coolshop-cdn.com',
  'www.euronics.de',
  'cdn.euronics.de',
  'www.galaxus.de',
  'www.galeria.de',
  'www.hornbach.de',
  'www.pieper.de',
  'www.rossmann.de',
  'www.aldi-onlineshop.de',
  'algolia.net',
  'algolianet.com',
  'cdns.eu1.gigya.com',
  'allesfuerzuhause.de',
  'www.aponeo.de',
  'cdn.idealo.com',
  'www.alternate.de',
  'www.actionsports.de',
  'www.bergfreunde.de',
  'www.action.com',
  'www.costway.de',
  'www.cyberport.de',
  'www.dm.de',
  'product-search.services.dmtech.com',
  'assets.dm.de',
  'products.dm.de',
  'content.services.dmtech.com',
  'www.fahrrad.de',
  'www.fressnapf.de',
  'fressnapf.app.baqend.com',
  'www.gamestop.de',
  'www.kaufland.de',
  'www.mediamarkt.de',
  'browserleaks.com',
  'www.metro.de',
  'www.mindfactory.de',
  'www.mueller.de',
  'static.mueller.de',
  'www.thalia.de',
  'www.otto.de',
  'www.quelle.de',
  'www.reichelt.de',
  'www.saturn.de',
  'www.sportspar.de',
  'www.voelkner.de',
  'www.zooplus.de',
  'www.idena.de',
  'www.amazon.de',
  'd29zc3pk4tzg0k.cloudfront.net',
  'sellercentral.amazon.de',
  'www.ebay.de',
  "ipinfo.io",
  // "fingerprintjs.github.io",
  // 'demo.fingerprint.com',
  // "dnsleaktest.com",
  // "eu.api.fpjs.io",
  // "fpjscdn.net",
  // "fingerprint.com",
  // "api.fpjs.pro",
  // "api.rollbar.com",
  // "api.github.com",
  // "www.whatsmyip.org",
  // "whoer.net",
  // "fv.pro",
  // "incolumitas.com",
  // "bot.incolumitas.com",
  // 'abs.incolumitas.com',
  // "tcpip.incolumitas.com",
  // "deviceandbrowserinfo.com",
  // "bot.sannysoft.com",
  // "cdn.jsdelivr.net",
  // "cdnjs.cloudflare.com",
];
